spring:
 jpa:
   show-sql: true
   open-in-view: false
   properties:
    hibernate:
      format_sql: true
      ddl-auto: false
      default_batch_fetch_size: 20
 datasource:
   url: jdbc:mysql://sh-cynosdbmysql-grp-jirpafw2.sql.tencentcdb.com:25255/cinema?useUnicode=true&characterEncoding=utf-8&useSSL=false
   username: dev
   password: Wyfdgg72
   driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8090


